[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/auth/reset-password"
  to = "/auth/reset-password.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 